services:
  editor:
    image: ghcr.io/natroutter/baudbound-editor:latest
    container_name: baudbound-editor
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_EDITOR_URL: "https://editor.baudbound.app"
